version: 2
jobs:
  deployprod:
    docker:
      - image: circleci/python:3
    steps:
      - add_ssh_keys:
         fingerprints:
            - "a2:08:0e:94:8f:47:d3:99:1b:8d:f5:27:d5:0a:fb:a9"
      - run:
          name: Deploy to the Prod Server
          command: |
                 ssh -o "StrictHostKeyChecking=no" $USER@$PROD_IP '
                     cd $BUILD_LOCATION
                     git checkout $CIRCLE_BRANCH &&
                     git reset --hard origin/$CIRCLE_BRANCH &&
                     git pull origin $CIRCLE_BRANCH
                     '
  deploytest:
    docker:
      - image: circleci/python:3
    steps:
      - add_ssh_keys:
         fingerprints:
            - "74:3b:67:37:b0:59:cd:a3:6c:27:e5:98:6f:92:59:3f"
      - run:
          name: Deploy to the Test Server
          command: |
                 ssh -o "StrictHostKeyChecking=no" $TEST_USER@$TEST_IP '
                     cd $TEST_BUILD_LOCATION
                     git checkout $CIRCLE_BRANCH &&
                     git reset --hard origin/$CIRCLE_BRANCH &&
                     git pull origin $CIRCLE_BRANCH
                     '
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deployprod:
          filters:
            branches:
              only:
                - master
      - deploytest:
          filters:
            branches:
              only:
                - test
